apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: configmapgenerators.custom.example.com
spec:
  group: custom.example.com
  names:
    kind: ConfigMapGenerator
    listKind: ConfigMapGeneratorList
    plural: configmapgenerators
    singular: configmapgenerator
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              key:
                type: string
              value:
                type: string
          status:
            type: object
            properties:
              status:
                type: string
