apiVersion: apps/v1
kind: Deployment
metadata:
  name: configmap-generator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configmap-generator
  template:
    metadata:
      labels:
        app: configmap-generator
    spec:
      containers:
      - name: configmap-generator
        image: your-docker-repo/configmap-generator:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
